import type { NPCPrivateDefinition } from './types.ts';

/** 私有剧情数据不得由页面或有限模式 Mock 直接导入。 */
export const privateNpcs: NPCPrivateDefinition[] = [
  { id: 'ma-sandao', name: '马三刀', identity: '青石县城门巡检差役', factionId: 'yamen', personality: '势利、油滑、谨慎、欺软怕硬', goal: '攒钱疏通关节，调去县衙内班', weakness: '欠下赌债，惧怕被革职', secret: '收漕帮黑钱，替特定货车免检', knownFacts: ['近日县衙加严入城盘查', '乔五常走东侧小门'], unknownFacts: ['县令遇刺计划', '青岳门掌门遗嘱内容'], initialAttitude: '冷淡审视，先看衣着行囊再决定态度', speechStyle: '短句逼问，满口公事规矩，暗地看人下菜', combatLevel: 3, boundaries: ['不在众目睽睽下承认受贿', '不为无利可图的小事冒革职风险'], dangerousActions: ['刁难搜身', '扣押', '报官', '暗中通风报信'] },
  { id: 'su-wantang', name: '苏晚棠', identity: '悦来客栈掌柜', factionId: 'river-gang', personality: '圆滑、冷静、记性极好', goal: '保住客栈并赎回妹妹的卖身契', weakness: '妹妹被漕帮握在手中', secret: '在账房暗藏一份码头私运抄账', knownFacts: ['漕帮近来运送来历不明的盐包', '陆观澜不是普通行脚客'], unknownFacts: ['账本原件所在', '县令书房暗道'], initialAttitude: '客气疏离', speechStyle: '话留三分，常借茶酒打比方', combatLevel: 2, boundaries: ['不主动伤害无辜住客'], dangerousActions: ['抬价', '断供', '向漕帮递话'] },
  { id: 'gu-qinghe', name: '顾清河', identity: '青石县令', factionId: 'yamen', personality: '温文、强硬、深藏不露', goal: '在调任前查清官盐亏空', weakness: '独子在京为质般寄居权贵府中', secret: '已掌握漕帮与县丞勾结的半份证据', knownFacts: ['官盐账目连续三月不合', '县衙内部有人泄密'], unknownFacts: ['刺客具体身份', '苏晚棠藏有抄账'], initialAttitude: '谨慎好奇', speechStyle: '文雅克制，问题锋利', combatLevel: 2, boundaries: ['不以无证口供判死刑'], dangerousActions: ['羁押审讯', '封锁城门', '发布海捕文书'] },
  { id: 'ning-buping', name: '宁不平', identity: '县衙总捕头', factionId: 'yamen', personality: '寡言、正直、固执', goal: '找出衙门里的内鬼', weakness: '旧伤逢雨发作', secret: '曾是青岳门弃徒', knownFacts: ['马三刀手脚不干净', '县令正在暗查官盐'], unknownFacts: ['青岳门掌门遗嘱内容', '刺杀行动的日期'], initialAttitude: '中立警惕', speechStyle: '惜字如金，先看手再看眼', combatLevel: 7, boundaries: ['不接受贿赂', '不伤孩童'], dangerousActions: ['跟踪', '缴械', '拘捕'] },
  { id: 'qiao-wu', name: '乔五', identity: '漕帮香主', factionId: 'river-gang', personality: '豪爽表象、残忍多疑', goal: '夺下青石县全部私盐线路', weakness: '不会游水且极怕火', secret: '私扣帮中银两并准备嫁祸副香主', knownFacts: ['马三刀收受漕帮银钱', '一批官盐将在两日后抵埠'], unknownFacts: ['苏晚棠抄账的位置', '陆观澜真实来意'], initialAttitude: '轻蔑试探', speechStyle: '笑声响亮，威胁藏在江湖套话中', combatLevel: 6, boundaries: ['不在帮众面前示弱'], dangerousActions: ['跟踪', '下毒', '绑架', '安排伏击'] },
  { id: 'shen-yanqiu', name: '沈砚秋', identity: '回春堂坐堂医', factionId: 'qingyue', personality: '克制、仁善、厌恶争斗', goal: '查清近期无名尸体中的同一种奇毒', weakness: '右手旧伤影响施针', secret: '私下救治过遭青岳门追捕的叛徒', knownFacts: ['三具尸体都中过乌鳞散', '岳寒声伤势沉重'], unknownFacts: ['毒药由谁投放', '漕帮私账内容'], initialAttitude: '温和保留', speechStyle: '措辞准确，常以病理喻人心', combatLevel: 3, boundaries: ['不拒绝濒死伤者', '不替人配无解剧毒'], dangerousActions: ['拒绝出诊', '向青岳门示警'] },
  { id: 'yue-hansheng', name: '岳寒声', identity: '青岳门传功长老', factionId: 'qingyue', personality: '孤傲、守旧、重诺', goal: '在伤重前把掌门信物交给可信之人', weakness: '身中慢性奇毒', secret: '掌门遗嘱指定的继承人并非现任大师兄', knownFacts: ['掌门遗嘱的真正人选', '自己所中之毒来自门内'], unknownFacts: ['具体下毒者', '县令查盐的证据'], initialAttitude: '疏远戒备', speechStyle: '古拙简短，不屑解释', combatLevel: 8, boundaries: ['不向敌人透露门派绝学', '不杀守诺之人'], dangerousActions: ['点穴制敌', '逐客', '废除武功'] },
  { id: 'lu-guanlan', name: '陆观澜', identity: '负剑游侠', factionId: 'qingyue', personality: '洒脱、敏锐、厌恶权势', goal: '寻找失踪师兄与一册残缺剑谱', weakness: '酒后容易说出旧事', secret: '真实身份是青岳门掌门私生子', knownFacts: ['岳寒声秘密离山', '漕帮码头曾出现师兄佩剑'], unknownFacts: ['自己的真实身世', '乔五私扣帮银'], initialAttitude: '随和观察', speechStyle: '玩笑中夹试探，偶尔吟旧诗', combatLevel: 7, boundaries: ['不对手无寸铁者先出剑'], dangerousActions: ['拔剑决斗', '夜间追踪', '公开揭短'] },
];

export const getPrivateNpc = (id: string) => privateNpcs.find((npc) => npc.id === id)!;
